import React from 'react';
import { ArrowLeft, Shield, FileText, RefreshCcw, X } from 'lucide-react';

const PageLayout = ({ icon: Icon, title, lastUpdated, children, onNavigate }) => {
  return (
    <div className="max-w-4xl mx-auto space-y-6 slide-up pb-8 pt-4">
      <div className="glass-card p-6 sm:p-8 group relative overflow-hidden">
        <button 
          onClick={() => onNavigate && onNavigate('dashboard')}
          className="absolute top-4 right-4 sm:top-6 sm:right-6 w-10 h-10 rounded-full bg-green-900/40 border border-green-800/50 flex items-center justify-center text-green-400 hover:bg-green-800 hover:text-green-200 transition-all z-20 backdrop-blur-md"
          title="Close / Go Back"
        >
          <X size={20} />
        </button>

        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 mb-6 pb-6 border-b border-green-800/30 pr-12">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-green-500/20 to-emerald-600/20 flex items-center justify-center shrink-0 border border-green-500/30">
            <Icon size={24} className="text-green-400" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-green-200">{title}</h1>
            <p className="text-xs sm:text-sm text-green-500/60 mt-1 font-medium">EFFECTIVE DATE: {lastUpdated}</p>
          </div>
        </div>
        
        <div className="prose prose-invert prose-green max-w-none text-green-100/80 prose-headings:text-green-300 prose-a:text-green-400 prose-strong:text-green-200 prose-ul:text-green-100/70">
          {children}
        </div>
      </div>
    </div>
  );
};

export const TermsView = ({ onNavigate }) => (
  <PageLayout icon={FileText} title="Terms & Conditions" lastUpdated="07 APR 2026" onNavigate={onNavigate}>
    <h3>1. Acceptance of Terms</h3>
    <p>
      By accessing or using the ALPHOVINS GLOBAL AGRO EXPORTS wholesale billing application 
      ("the Service"), you agree to be bound by these comprehensive Terms. If you disagree with any part of 
      the terms, you may not access the Service. These terms constitute a legally binding agreement in accordance with the Indian Contract Act, 1872.
    </p>

    <h3>2. Wholesale Agricultural Trading execution</h3>
    <p>
      ALPHOVINS operates strictly as a B2B agricultural wholesale entity. All buyers, agents, and 
      merchants interacting with our platform acknowledge that transactions involve bulk, 
      market-dependent agricultural goods (primarily Banana varieties). 
      <strong>Daily Rate Fluctuation:</strong> Rates of agricultural produce are highly volatile. The "Rate per KG" is considered final and binding at the exact moment of weighing and billing on our trading floor.
    </p>

    <h3>3. Payment & Settlement Terms</h3>
    <p>
      All payments must be completed via the provided Payment Gateway links (UPI/NEFT/RTGS) or authorized cash channels. 
      Pending accounts beyond a <strong>7-day grace period</strong> may be subject to restricted future trades at management discretion. 
      Invoices and bills generated by this system electronically trace gross weights, agreed wastage deductions, 
      and the final net weight financial settlement values.
    </p>

    <h3>4. Force Majeure (Acts of God)</h3>
    <p>
      ALPHOVINS shall not be liable for any failure or delay in the dispatch, transport, or quality preservation of agricultural goods arising out of causes beyond our reasonable control, including but not limited to unseasonal weather, natural disasters, strikes, transport disruptions, or government restrictions.
    </p>

    <h3>5. Governing Law & Jurisdiction</h3>
    <p>
      These Terms shall be governed and construed in accordance with the laws of India. Any disputes arising in connection with bulk trading, wastage deductions, or financial settlements shall be exclusively subject to the jurisdiction of the competent courts of <strong>Tamil Nadu</strong>.
    </p>
  </PageLayout>
);

export const PrivacyView = ({ onNavigate }) => (
  <PageLayout icon={Shield} title="Privacy Policy" lastUpdated="07 APR 2026" onNavigate={onNavigate}>
    <h3>1. Information Collection</h3>
    <p>
      We collect minimal necessary B2B data to facilitate direct wholesale agricultural trades and ledger maintenance. 
      This includes:
    </p>
    <ul>
      <li>Merchant entity names, GSTIN (if applicable), and authorized representative profiles.</li>
      <li>Phone numbers and WhatsApp accounts primarily used for official invoicing communications.</li>
      <li>Detailed historical transaction, weighing, and billing data.</li>
    </ul>

    <h3>2. WhatsApp & Electronic Communication Consent</h3>
    <p>
      By registering as a merchant or utilizing our services, you grant explicit consent for ALPHOVINS to transmit electronic invoices, outstanding payment reminders, and daily market rate updates directly to your registered WhatsApp mobile number or Email.
    </p>

    <h3>3. Data Sharing & Third-Party Gateways</h3>
    <p>
      ALPHOVINS GLOBAL AGRO EXPORTS does <strong>NOT</strong> sell, trade, or transfer 
      your proprietary business or pricing information to external competitors. We only transmit minimum viable data to trusted 
      third-party infrastructure (such as Firebase for cloud hosting and Payment Gateways like PhonePe/Razorpay).
    </p>

    <h3>4. Data Security & Retention</h3>
    <p>
      We implement secure, encrypted cloud infrastructure protocols to maintain the integrity of your offline business 
      details and transaction logs. In compliance with Indian tax laws, financial ledgers and generated PDF invoices are securely retained for a minimum of 8 financial years.
    </p>
  </PageLayout>
);

export const RefundView = ({ onNavigate }) => (
  <PageLayout icon={RefreshCcw} title="Cancellation & Refund Policy" lastUpdated="07 APR 2026" onNavigate={onNavigate}>
    <h3>1. Status of Perishable Goods</h3>
    <p>
      ALPHOVINS GLOBAL AGRO EXPORTS deals strictly in raw, untreated wholesale agricultural produce (Bananas), 
      which are strictly classified as <strong>Highly Perishable Goods</strong> under consumer and trade laws.
    </p>

    <h3>2. Cancellation Timeline</h3>
    <p>
      Due to the heavy logistics of wholesale truck loading and the rapid spoilage nature of the produce, 
      orders <strong>cannot be cancelled or modified</strong> once the goods have been officially weighed on the floor, finalized, and loaded for dispatch.
    </p>

    <h3>3. Wastage Claims & Refund Mechanism</h3>
    <p>
      Because our goods are highly perishable, we generally operate under a strict <strong>No Return Policy</strong> 
      post-dispatch. Fair trade disputes are handled as follows:
    </p>
    <ul>
      <li>
        <strong>On-Floor Deductions:</strong> Visible spoilage or natural weight loss must be assessed, negotiated, 
        and documented under the "Wastage" metric at the time of standard weighing <em>before</em> the trader leaves the premises.
      </li>
      <li>
        <strong>Transit Damage Claims:</strong> Any drastic weight discrepancies, abnormal ripening, or transit total-loss claims must 
        be reported with photographic evidence <strong>within 6 hours</strong> of delivery. Claims made after this window will 
        be automatically disqualified due to the nature of the goods.
      </li>
      <li>
        <strong>Ledger Adjustment:</strong> Instead of initiating a direct cash refund, if a fair claim is mutually verified by ALPHOVINS management, we reserve the 
        right to credit the disputed amount toward your <strong>next bulk purchase ledger</strong>.
      </li>
    </ul>
  </PageLayout>
);
