import React from 'react';
import { ArrowLeft, Shield, FileText, RefreshCcw } from 'lucide-react';

const PageLayout = ({ icon: Icon, title, lastUpdated, children }) => {
  return (
    <div className="max-w-4xl mx-auto space-y-6 slide-up pb-8">
      <div className="glass-card p-8">
        <div className="flex items-center gap-4 mb-6 pb-6 border-b border-green-800/30">
          <div className="w-12 h-12 rounded-xl bg-green-500/10 flex items-center justify-center">
            <Icon size={24} className="text-green-400" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-green-200">{title}</h1>
            <p className="text-sm text-green-500/50 mt-1">Last Updated: {lastUpdated}</p>
          </div>
        </div>
        
        <div className="prose prose-invert prose-green max-w-none text-green-100/80 prose-headings:text-green-300 prose-a:text-green-400">
          {children}
        </div>
      </div>
    </div>
  );
};

export const TermsView = () => (
  <PageLayout icon={FileText} title="Terms & Conditions" lastUpdated="April 2026">
    <h3>1. Acceptance of Terms</h3>
    <p>
      By accessing or using the ALPHOVINS GLOBAL AGRO EXPORTS wholesale billing application 
      ("the Service"), you agree to be bound by these Terms. If you disagree with any part of 
      the terms, then you may not access the Service.
    </p>

    <h3>2. B2B Wholesale Trading</h3>
    <p>
      ALPHOVINS operates strictly as a B2B agricultural wholesale entity. All buyers and 
      merchants interacting with our platform acknowledge that transactions involve bulk, 
      raw agricultural goods (primarily Banana varieties).
    </p>

    <h3>3. Payment Terms</h3>
    <p>
      All payments must be completed via the provided Payment Gateway links or offline channels. 
      Pending accounts may be subject to restricted future trades at management discretion. 
      Invoices and bills generated by this system trace gross weights, wastage deductions, 
      and net weight financial settlement values.
    </p>

    <h3>4. Limitation of Liability</h3>
    <p>
      In no event shall ALPHOVINS GLOBAL AGRO EXPORTS be liable for any indirect, incidental, 
      special, consequential or punitive damages resulting from your access to or use of, 
      or inability to access or use the Service.
    </p>

    <h3>5. Governing Law</h3>
    <p>
      These Terms shall be governed and construed in accordance with the laws of India, 
      specifically subject to the jurisdiction of the courts of Tamil Nadu, without regard 
      to its conflict of law provisions.
    </p>
  </PageLayout>
);

export const PrivacyView = () => (
  <PageLayout icon={Shield} title="Privacy Policy" lastUpdated="April 2026">
    <h3>1. Information Collection</h3>
    <p>
      We collect minimal necessary business data to facilitate direct wholesale agricultural trades. 
      This includes:
    </p>
    <ul>
      <li>Merchant entity names and authorized representative names.</li>
      <li>Phone numbers (primarily used for WhatsApp billing and direct communication).</li>
      <li>Historical transaction and billing data.</li>
    </ul>

    <h3>2. Use of Information</h3>
    <p>
      The collected information is solely used for:
    </p>
    <ul>
      <li>Processing transactions and generating electronic invoices/bills.</li>
      <li>Facilitating payment processing via our secure Payment Gateway partners.</li>
      <li>Internal accounting and reporting.</li>
    </ul>

    <h3>3. Data Sharing</h3>
    <p>
      ALPHOVINS GLOBAL AGRO EXPORTS does <strong>NOT</strong> sell, trade, or otherwise transfer 
      your personally identifiable information to outside third parties. This does not include trusted 
      third parties (such as Payment Gateways e.g. PhonePe, Razorpay) who assist us in operating 
      our platform, conducting our business, or servicing you, so long as those parties agree to 
      keep this information confidential.
    </p>

    <h3>4. Data Security</h3>
    <p>
      We implement secure cloud infrastructure (Firebase) to maintain the safety of your business 
      details and transaction logs. All sensitive transaction data is handled over secure protocols.
    </p>
  </PageLayout>
);

export const RefundView = () => (
  <PageLayout icon={RefreshCcw} title="Cancellation & Refund Policy" lastUpdated="April 2026">
    <h3>1. Nature of Goods</h3>
    <p>
      ALPHOVINS GLOBAL AGRO EXPORTS primarily deals in raw, wholesale agricultural produce (Bananas), 
      which are strictly classified as <strong>Perishable Goods</strong>.
    </p>

    <h3>2. Cancellation Policy</h3>
    <p>
      Due to the logistics of wholesale trade and the rapid spoilage nature of the produce, 
      orders cannot be cancelled once the goods have been weighed, finalized, and dispatched 
      from our trading floor.
    </p>

    <h3>3. Refund & Return Policy</h3>
    <p>
      Because our goods are highly perishable, we operate under a strict <strong>No Return Policy</strong> 
      post-dispatch. However, we ensure fair trade through the following mechanism:
    </p>
    <ul>
      <li>
        <strong>Wastage Deductions:</strong> Visible spoilage or wastage must be assessed, negotiated, 
        and documented at the time of standard weighing <em>before</em> the final bill is generated.
      </li>
      <li>
        <strong>Valid Claims:</strong> Any drastic weight discrepancies or transit total-loss claims must 
        be reported <strong>within 12 hours</strong> of delivery. Claims made after this window will 
        be automatically disqualified.
      </li>
      <li>
        <strong>Refund Method:</strong> If a fair claim is mutually verified, ALPHOVINS reserves the 
        right to credit the disputed value toward your <strong>next bulk purchase</strong> rather than 
        initiating a direct cash refund, dependent on business circumstances.
      </li>
    </ul>
  </PageLayout>
);
